CpfCnpjValidator fix
pedrooalves/goCharges pull request #19
Opened 2023-05-25 18:30 UTC by GabrielPradoAsaas

### Impacto
- Alterando método validate

### PR Predecessora
- Não possui

2023-05-25 19:06 UTC, Kpotz commented on src/main/groovy/gocharges/validator/CpfCnpjValidator.groovy
>          }
Assim evita fazer o length duas vezes na string
```suggestion
        Integer cpfCnpjLength = cpfCnpj.length()
        if(cpfCnpjLength != 11 && cpfCnpjLength != 14){
            throw new BusinessException("Informe um tamanho de CPF / CNPJ correto.")
        }
```

2023-05-26 12:05 UTC, pedrooalves approved these changes

2023-05-26 16:09 UTC, pedrooalves approved these changes

2023-05-31 14:52 UTC, welingtonloh requested changes

2023-05-31 17:06 UTC, pedrooalves commented on src/main/groovy/gocharges/validator/CpfCnpjValidator.groovy
> +         Integer cpfCnpjLength = cpfCnpj.length()
Alterações de encorpamento feitas, única diferença são as exceções.

2023-05-31 21:43 UTC, welingtonloh commented
Tem coisa errada com o merge desse?

2023-06-01 16:18 UTC, pedrooalves commented
Não sei se algum conflito direto, mas por ter dado algum e ter subido 800 linhas de mudanças juntas que são mudanças que estão sendo revisadas nos outros PRs e pra facilitar leitura e revisão, repassei para este PR: 
https://github.com/pedrooalves/goCharges/pull/32

2023-06-02 15:15 UTC, closed without merging