User login
pedrooalves/goCharges pull request #21
Opened 2023-05-26 16:58 UTC by GabrielPradoAsaas

### Impacto
- Autenticação de usuário com Spring Security
- Só é possível acessar a tela customer se o usuário logado for admin

Obs: Essa PR está extensa, porque todas as classes de Domínio (User, Role e UserRole) foram geradas pelo próprio Spring Security

### PR Predecessora
- Não possui

2023-05-30 17:17 UTC, pedrooalves approved these changes

2023-05-31 14:59 UTC, welingtonloh requested changes

2023-05-31 14:59 UTC, welingtonloh commented on grails-app/domain/gocharges/auth/Role.groovy
> +		authority nullable: false, blank: false, unique: true
Dá uma conferida nessa indentação, esse tab tá estranho

2023-05-31 14:59 UTC, welingtonloh commented on grails-app/domain/gocharges/auth/User.groovy
> +	    password column: '`password`'
indentação

....

Validar o PR inteiro em relação a isso

2023-06-02 15:16 UTC, welingtonloh approved these changes

2023-06-02 15:16 UTC, merged