User sign up
pedrooalves/goCharges pull request #23
Opened 2023-05-29 12:10 UTC by GabrielPradoAsaas

### Impacto
- Cadastro de User criado
- Repositories de User, Role e UserRole foram criados

### PR Predecessora
- https://github.com/pedrooalves/goCharges/pull/21

2023-05-29 19:01 UTC, pedrooalves approved these changes

2023-05-31 15:21 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +        if(chainModel) {
```suggestion
        if (chainModel) {
```
O que o chainModel faz exatamente?

2023-05-31 15:21 UTC, welingtonloh commented on grails-app/services/gocharges/UserService.groovy
> +            throw new BusinessException("É preciso preencher todos os campos")
É preciso ser o mais claro possivel com o usuario, indicando qual campo ele precisa preencher.

2023-05-31 15:21 UTC, welingtonloh commented on grails-app/views/user/signup.gsp
> +    <g:if test="${validation && (validation.type == 'delete' || validation.type == 'update' ||
É, temos que nos livrar disso aqui, esse código não tá muito legal

o uso de flash message torna esses tratamentos desnecessários

2023-05-31 15:21 UTC, welingtonloh commented on grails-app/views/user/signup.gsp
> +        E-mail
Pq não envolver em label?

2023-05-31 15:21 UTC, welingtonloh commented on grails-app/views/user/signup.gsp
> +<g:form method='POST' id='signUp' name='signUp' url="[controller: 'user', action: 'save']">
Deixa bem indentado

2023-05-31 15:21 UTC, welingtonloh commented on grails-app/services/gocharges/UserService.groovy
> +        Role role = RoleRepository.query([authority: "ROLE_USER"]).get()
ROLE_USER >> Cria uma Enum de RoleAuthority

2023-05-31 15:21 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/role/RoleRepository.groovy
> +                eq("authority", search.authority)
```suggestion
                eq("authority", RoleAuthority.valueOf(search.authority))
```

2023-06-01 12:10 UTC, GabrielPradoAsaas commented on grails-app/controllers/gocharges/UserController.groovy
> +        if(chainModel) {
> O que o chainModel faz exatamente?

Passa um model para outro método, nesse caso passa um map de validação para tratarmos erros na view, mas já trocamos para flash.message na PR 28

2023-06-02 15:31 UTC, welingtonloh requested changes

2023-06-02 15:31 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +            Map validation = [success:true, message:"Conta criada com sucesso", type:"save"]
```suggestion
            Map validation = [success:true, message: "Conta criada com sucesso", type: "save"]
```

2023-06-02 15:31 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +            chain(action: "signUp", model:[validation:validation])
```suggestion
            chain(action: "signUp", model: [validation:validation])
```

2023-06-02 15:31 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +        } catch(BusinessException e) {
```suggestion
        } catch(BusinessException businessException) {
```

2023-06-02 15:31 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +            Map validation = [success:false, message:e.getMessage(), type:"save"]
```suggestion
            Map validation = [success: false, message: e.getMessage(), type: "save"]
```

2023-06-02 15:31 UTC, welingtonloh commented on grails-app/services/gocharges/UserService.groovy
> +            throw new BusinessException("O campo e-mail é obrigatório")
Passem a utilizar o message.properties:
default.null.message=O campo {0} deve ser informado
if (!value) throw new BusinessException(Utils.getMessageProperty("default.null.message", ["valor"]))

2023-06-02 15:31 UTC, welingtonloh commented on grails-app/services/gocharges/UserService.groovy
> +        if(params.password.isBlank()) {
```suggestion
        if (!params.password) {
```
Validar todos

2023-06-02 15:31 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/role/RoleRepository.groovy
> +            if(search.containsKey("authority")) {
```suggestion
            if (search.containsKey("authority")) {
```

2023-06-02 15:31 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/role/RoleRepository.groovy
> +                eq("authority", search.authority.toString())
```suggestion
                eq("authority", RoleAuthority.valueOf(search.authority.toString()))
```

2023-06-02 15:31 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/user/UserRepository.groovy
> +            if(search.containsKey("username")) {
```suggestion
            if (search.containsKey("username")) {
```

2023-06-02 15:31 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/userrole/UserRoleRepository.groovy
> +            if(search.containsKey("user")) {
```suggestion
            if (search.containsKey("user")) {
```

2023-06-05 13:16 UTC, merged