User update
pedrooalves/goCharges pull request #25
Opened 2023-05-29 17:59 UTC by GabrielPradoAsaas

### Impacto
- Update básico de User criado

### PR Predecessora
- https://github.com/pedrooalves/goCharges/pull/23

2023-05-29 18:54 UTC, pedrooalves approved these changes

2023-05-31 15:26 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +        } catch (BusinessException e) {
```suggestion
        } catch (BusinessException businessException) {
```

2023-05-31 15:29 UTC, welingtonloh commented on grails-app/services/gocharges/UserService.groovy
> +        user.save(failOnError: true)
```suggestion
        return user.save(failOnError: true)
```
Mais direto

2023-06-02 15:37 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/user/UserRepository.groovy
> +            if(search.containsKey("id")) {
```suggestion
            if (search.containsKey("id")) {
```

2023-06-02 15:37 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/user/UserRepository.groovy
> +                eq("id", search.id)
```suggestion
                eq("id", Long.valueOf(search.id))
```

2023-06-02 15:37 UTC, welingtonloh commented on src/main/groovy/gocharges/auth/user/adapter/UserAdapter.groovy
> +        if(params.containsKey("currentPassword")) {
Não deveria ter lógica de negócio no adapter

Pq precisam da senha antiga?

2023-06-02 17:03 UTC, GabrielPradoAsaas commented on src/main/groovy/gocharges/auth/user/adapter/UserAdapter.groovy
> +        if(params.containsKey("currentPassword")) {
> Não deveria ter lógica de negócio no adapter
> 
> Pq precisam da senha antiga?

A ideia é o usuário informar a senha quando quiser alterar alguma informação. Eu removi a lógica do adapter e agora quem trata isso é o Service.

2023-06-05 14:04 UTC, pedrooalves commented on grails-app/controllers/gocharges/CustomerController.groovy
>          try{
```suggestion
        try {
```

2023-06-05 14:04 UTC, pedrooalves commented on grails-app/controllers/gocharges/PaymentController.groovy
>          try{
```suggestion
        try {
```

2023-06-06 16:20 UTC, pedrooalves requested changes

2023-06-06 16:43 UTC, pedrooalves approved these changes

2023-06-06 18:18 UTC, GabrielPradoAsaas commented
Conflitos resolvidos

2023-06-07 01:38 UTC, welingtonloh commented on grails-app/controllers/gocharges/UserController.groovy
> +            userService.update(id, adapter, currentPassword)
O certo é chamarmos o validateUpdate dentro do proprio update

2023-06-07 12:07 UTC, pedrooalves approved these changes

2023-06-09 13:13 UTC, merged