[Parte 1] Implementação do Comprovante de Pagamento
pedrooalves/goCharges pull request #41
Opened 2023-06-07 15:02 UTC by pedrooalves

### Impacto
- Implementação da funcionalidade de gerar comprovante de pagamento.
- Após cobrança ser confirmada, será possível gerar e acessar o comprovante da mesma.

### Release Note (Descrição que irá no forno)

### PR Predecessora
- https://github.com/pedrooalves/goCharges/pull/30

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA / Trello
- https://trello.com/c/Nqy86nKE

### Link dos mockups

### Prints do desenvolvimento

2023-06-07 17:29 UTC, GabrielPradoAsaas commented on grails-app/views/payment/index.gsp
> +                    <g:form name="voucherButton" url="[controller: 'paymentReceipt', action: 'index']" method="GET">
```suggestion
                    <g:form name="receiptButton" url="[controller: 'paymentReceipt', action: 'index']" method="GET">
```

2023-06-13 20:22 UTC, welingtonloh requested changes

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/domain/gocharges/Payment.groovy
> +    String publicId = UUID.randomUUID().toString().replace("-", "")
Coloca essa regra dentro do método save na service

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/controllers/gocharges/PaymentReceiptController.groovy
> +            Payment payment = paymentService.getReceipt(params.publicId)
Pq precisa retornar a payment?

troca por buildReceipt, get parece que está retornando um atributo da classe

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/views/paymentReceipt/index.gsp
> +</body>
Capricha na indentação

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/views/paymentReceipt/index.gsp
> +                <p class="mb-2"></p>
Ué, cadê a data?

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/views/paymentReceipt/index.gsp
> +                <p class="mb-2">${payment.value}</p>
Não vai indica que é monetário? R$

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/views/paymentReceipt/index.gsp
> +                <p class="font-weight-bold mr-2">Método de pagamento:</p>
Forma de pagamento

2023-06-13 20:22 UTC, welingtonloh commented on grails-app/views/paymentReceipt/index.gsp
> +    <div class="container d-flex justify-content-center mt-5">
Senti falta da data/hora de emissão

2023-06-13 20:22 UTC, welingtonloh commented on src/main/groovy/gocharges/payment/PaymentRepository.groovy
> +            if (search.containsKey("id")) {
Long.valueOf

2023-06-13 20:22 UTC, welingtonloh commented on src/main/groovy/gocharges/payment/PaymentRepository.groovy
> +            if (search.containsKey("status")) {
PaymentStatus.valueOf

2023-06-14 18:42 UTC, pedrooalves commented on grails-app/views/paymentReceipt/index.gsp
> +                <p class="mb-2"></p>
Implementado o paymentDate que veio do Confirmar Pagamento
- https://github.com/pedrooalves/goCharges/pull/24/files#diff-bf9b83425eb76bac19cdb5bfbedad0f0e1db57217d26160e6fed38729dcd2f98

2023-06-14 21:07 UTC, welingtonloh approved these changes

2023-06-14 21:07 UTC, merged