TagLib de Formatações
pedrooalves/goCharges pull request #46
Opened 2023-06-09 14:54 UTC by pedrooalves

### Impacto
- Adição da TagLib de formatações (Cpf, Cnpj, Datas e Métodos de Pagamento)

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA / Trello

### Link dos mockups

### Prints do desenvolvimento

2023-06-09 16:14 UTC, welingtonloh commented on grails-app/taglib/gocharges/FormatTagLib.groovy
> +            out << attrs.cpfCnpj.substring(0, 3) + "." + attrs.cpfCnpj.substring(3, 6) + "." + attrs.cpfCnpj.substring(6, 9) + "-" +
Vale a pena?
Deixa sem por enquanto, depois tratamos isso via mascara JS no front

2023-06-09 16:14 UTC, welingtonloh commented on grails-app/taglib/gocharges/FormatTagLib.groovy
> +        if (attrs.billingType == PaymentBillingType.BANK_SLIP) {
Dá para colocar essa tradução no message.properties

E acessar a msg via codigo: TYPE.label="Tradução"

2023-06-09 16:55 UTC, pedrooalves commented on grails-app/taglib/gocharges/FormatTagLib.groovy
> +            out << attrs.cpfCnpj.substring(0, 3) + "." + attrs.cpfCnpj.substring(3, 6) + "." + attrs.cpfCnpj.substring(6, 9) + "-" +
Beleza, fica como um alerta pra implementar o PersonType também né? Para não ter que ficar sempre validando por tamanho

2023-06-12 21:38 UTC, welingtonloh requested changes

2023-06-12 21:38 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
> +PaymentType.BANK_SLIP=Boleto
```suggestion
BillingType.BANK_SLIP=Boleto
```

2023-06-12 21:42 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
> +PaymentType.PIX=Pix
```suggestion
BillingType.DEBIT_CARD=Cartão de Débito
BillingType.PIX=Pix
```

2023-06-12 21:43 UTC, welingtonloh commented on grails-app/taglib/gocharges/FormatTagLib.groovy
> +        String messageCode = "PaymentType." + attrs.billingType.toString()
```suggestion
        String messageCode = "BillingType." + attrs.billingType.toString()
```

2023-06-12 21:43 UTC, welingtonloh approved these changes

2023-06-12 21:43 UTC, merged