Confirmar método de pagamento em dinheiro
pedrooalves/goCharges pull request #52
Opened 2023-06-12 19:17 UTC by pedrooalves

### Impacto
- Alteração da funcionalidade de confirmar pagamento, que antes tinha a funcionalidade somente de confirmar qualquer cobrança pendente, agora tem a funcionalidade de confirmar que uma cobrança foi paga em dinheiro (CASH)
- Implementação dos PopUp Alerts (Modal) do Bootstrap para solicitar a confirmação do usuário.

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA / Trello
- https://trello.com/c/7xq6Btux

### Link dos mockups

### Prints do desenvolvimento

2023-06-12 21:37 UTC, welingtonloh requested changes

2023-06-12 21:37 UTC, welingtonloh commented on grails-app/services/gocharges/PaymentService.groovy
> +        payment.billingType = PaymentBillingType.CASH
Precisa validar o status da cobrança, senão for o status que é permitido deve emitir uma BE explicando

2023-06-13 15:43 UTC, welingtonloh commented on grails-app/views/payment/index.gsp
> +                    <li class="custom-list-item col"><FormatTagLib:brazilDateNotation date="${payment.dueDate}"/></li>
Aqui precisa da forma que está escrito aqui:
static namespace = "formatTagLib"

2023-06-13 15:44 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
> +default.not.pending.payment.message=S� � poss�vel confirmar o pagamento de cobran�as pendentes
Mexeu no encoding da IDE?

2023-06-13 18:25 UTC, pedrooalves commented on grails-app/i18n/messages_pt_BR.properties
> +default.not.pending.payment.message=S� � poss�vel confirmar o pagamento de cobran�as pendentes
Não, faltou traduzir a mensagem para o encoding do arquivo, mas agora já está traduzido.

2023-06-13 21:14 UTC, welingtonloh commented on src/main/groovy/gocharges/payment/enums/PaymentBillingType.groovy
> +    CASH
CREDIT_CARD

2023-06-13 21:14 UTC, welingtonloh commented on grails-app/views/payment/index.gsp
> +                <div id="customAlert">
Chama de modal de confirmação de recebimento em dinheiro, importa o template inteiro da modal aqui

2023-06-15 19:30 UTC, welingtonloh commented on grails-app/assets/javascripts/modalController.js
> +
```suggestion
```

2023-06-19 13:10 UTC, merged